### ISSUE TITLE
Non-hierarchical URI's in Intent-data crash

### ISSUE THREAD

**Issue by SleeplessByte** [BranchMetrics/Branch-Android-SDK#28]
Setting an Intent's data to a Non-hierarchical URI invokes a crash. The data wasn't intended for Branch in the first place.

````
[...]
     Caused by: java.lang.UnsupportedOperationException: This isn't a hierarchical URI.
            at android.net.Uri.getQueryParameter(Uri.java:1662)
            at io.branch.referral.Branch.initSession(Branch.java:168)
            at com.paystik.droid.behaviors.BranchMetricsBehavior.initSession(BranchMetricsBehavior.java:106)
            at com.paystik.droid.behaviors.BranchMetricsBehavior.onAction(BranchMetricsBehavior.java:63)
            at com.paystik.droid.activities.BaseActivity.onAction(BaseActivity.java:264)
            at com.paystik.droid.behaviors.BranchMetricsBehavior.initSession(BranchMetricsBehavior.java:188)
            at com.paystik.droid.activities.BaseActivity.onStart(BaseActivity.java:157)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
            at android.app.Activity.performStart(Activity.java:5241)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2178)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
````

**Comment by aaustin** [comment]
Oh interesting - let me resolve that in a second. For my knowledge: what URI are you using and what for?

**Comment by aaustin** [comment]
Hey @SleeplessByte - the latest Github, JAR and zip have this issue resolved. Please try it on for size

**Comment by SleeplessByte** [comment]
@aaustin I am syncing it now :+1:

**Comment by SleeplessByte** [comment]
Confirmed working. FYI: `mailto:email@example.org` is opaqu (non-hier)
